# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 899516a978c7d10c7328e395a2c78e56cd8a63103e95c53a666c89366d9d75f960045612453f8378ae1fb5e7f53a4a55a7fbae6ea2d4d30bf845e7734b977ea6

test:
  secret_key_base: b619e4351d061e26103a9506c7b87fc9a16a13649d0bfcc6a3129132df29de061c6b6e5fa3c919ad8922fd198c3a2f1c20fd5be8cfd16311d70bc82c28d95c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
